### PR TITLE
Skip N/A values from ffmpeg progress

### LINKED ISSUE #178: ParseUtil
```
03:21:59.689 [StdErr] INFO  c.g.k.j.f.FFmpegResultReader - [info] frame= 5400 fps=0.0 q=-1.0 Lsize=N/A time=00:02:59.97 bitrate=N/A speed=3.09e+03x    
03:21:59.690 [Runnable-0] WARN  c.g.k.j.u.ParseUtil - Failed to parse long number: N/A
java.lang.NumberFormatException: For input string: "N/A"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Long.parseLong(Long.java:692) ~[?:?]
	at java.lang.Long.parseLong(Long.java:817) ~[?:?]
	at com.github.kokorin.jaffree.util.ParseUtil.parseLong(ParseUtil.java:53) [classes/:?]
	at com.github.kokorin.jaffree.ffmpeg.FFmpegProgressReader.readProgress(FFmpegProgressReader.java:101) [classes/:?]
	at com.github.kokorin.jaffree.ffmpeg.FFmpegProgressReader.negotiate(FFmpegProgressReader.java:54) [classes/:?]
	at com.github.kokorin.jaffree.net.NegotiatingTcpServer.serve(NegotiatingTcpServer.java:44) [classes/:?]
	at com.github.kokorin.jaffree.net.TcpServer.run(TcpServer.java:66) [classes/:?]
	at com.github.kokorin.jaffree.process.Executor$1.run(Executor.java:83) [classes/:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### PR DESCRIPTION
**Pull request by cromefire**
Fixes #178

If a value is set to `N/A` it's essentially the equivalent of `null`, so it's probably good to treat it like that.

### CODE REVIEW

**Comment by cromefire** [comment]
`testShowFrames` seems to be failing but it seems to also do so on the master branch

**Comment by kokorin** [comment]
Please, make sure that changed functionality is covered with tests

**Comment by kokorin** [comment]
Please, read contributor's guide: PRs should be created from develop branch

**Comment by cromefire** [comment]
Made a replacement that should satisfy your requirements

**Pull request closed without merging**
