### PR TITLE
Added JaffreeException for easier ExceptionHandling for consumers

### PR DESCRIPTION
**Pull request by Dan-Mikkel**

### CODE REVIEW

**Comment by Dan-Mikkel** [comment]
I apologize if i made a hassle by making 2 pull requests, but i hope you'll consider these changes i've proposed.

**Comment by kokorin** [comment]
@Dan-Mikkel no worries.

**Comment by kokorin** [comment]
@Dan-Mikkel notice: not sure when the next release will be

**Comment by Dan-Mikkel** [comment]
That's fair, i'll be waiting in the meantime. Thank you.

tor. 18. feb. 2021, 07:15 skrev Denis Kokorin <notifications@github.com>:

**Comment by kokorin** [comment]
Check 0.10.0 version, will be available in Maven Central in few hours

**Comment by kokorin** [comment]
Also I noticed that you didn't add Apache v2 Copyright Notice to `JaffreeException`.  I did it on behalf of you. If you don't agree to share your changes under Apache v2 License - please let me know

**Comment by Dan-Mikkel** [comment]
Ah, that's fine by me. Did not realize i had to do that, will remember for my next contribution.

**Pull request merged**
