### PR TITLE
Issue 195: index out of bounds in NutReader

### PR DESCRIPTION
**Pull request by marklassau**
Proposed fix for ArrayIndexOutOfBoundsException at NutReader.readToFrame(NutReader.java:126)

### CODE REVIEW

**Review by kokorin — CHANGES_REQUESTED** [review]
@marklassau thank you for your work. The PR is very short and clear.

Could you, please, add yourself to Apache copyright notice in NutReader class?

**Comment by kokorin** [comment]
@marklassau Please, fix checkstyle:
```
INFO] --- maven-checkstyle-plugin:3.1.2:check (default) @ jaffree ---
[INFO] There is 1 error reported by Checkstyle 8.45 with checkstyle.xml ruleset.
Error:  src/main/java/com/github/kokorin/jaffree/nut/NutReader.java:[3] (header) Header: Line does not match expected header line of ' *'.
```

Copyright should contain author names comma-separated.

**Comment by marklassau** [comment]
> Copyright should contain author names comma-separated.

OK, I will take `FFmpeg.java` as an example which looks like this:

```
 *    Copyright 2017-2021 Denis Kokorin, Oded Arbel
```

So I shall put "Copyright 2017-2021" for the year?

**Comment by kokorin** [comment]
@marklassau exactly

**Pull request merged**
